name: primera:automatizacion
on:
push:
branches:
main
jobs:
say cambios:
runs-on: ubuntu-latest
steps:
- name: Checkout code
user: actions/checkout@v3
- name: Print PrimeraAutomatizacion
run: echo " Automatizacion, GitHub Action!"

