name: primera
on:
  push:
    branches:
      - master

jobs:
  say-cambios:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print PrimeraAutomatizacion
        run: echo "Automatizacion, GitHub Action!"
